# Generated by Django 3.2.18 on 2023-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='category',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(choices=[('art_photography_creative', 'Art, Photography & Creative Services'), ('construction_home_improvement', 'Construction & Home Improvement'), ('consulting_professional', 'Consulting & Professional Services'), ('financial_services_insurance', 'Financial Services & Insurance'), ('hair_spa_aesthetics', 'Hair, Spa & Aesthetics'), ('nonprofits_associations_groups', 'Non-profits, Associations & Groups'), ('real_estate', 'Real Estate'), ('retailers_resellers_sales', 'Retailers, Resellers & Sales'), ('web_tech_media', 'Web, Tech & Media'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
