# Generated by Django 3.2.18 on 2023-04-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0002_alter_job_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('after hours', 'After Hours'), ('standard', 'Standard'), ('vip', 'VIP'), ('warranty', 'Warranty')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('partially paid', 'Partially Paid'), ('paid', 'Paid'), ('late', 'Late Payment'), ('pending', 'Pending Payment'), ('overdue', 'Overdue'), ('not invoiced', 'Not Yet Invoiced'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('quote', 'Quote'), ('work order', 'Work Order'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='quote', max_length=20),
        ),
    ]
