# Generated by Django 3.1.7 on 2023-03-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0002_remove_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='user_photos/default-avatar.png', upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
