# Generated by Django 3.1.7 on 2023-03-30 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0004_auto_20230329_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('check', 'Check'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('late', 'Late Payment'), ('pending', 'Pending Payment'), ('overdue', 'Overdue'), ('not_invoiced', 'Not Yet Invoiced'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
