# Generated by Django 3.2.18 on 2023-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0005_invoice_color_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(choices=[('art, photography & creative', 'Art, Photography & Creative Services'), ('construction & home improvement', 'Construction & Home Improvement'), ('consulting & professional', 'Consulting & Professional Services'), ('financial services & insurance', 'Financial Services & Insurance'), ('hair, spa & aesthetics', 'Hair, Spa & Aesthetics'), ('non-profits, associations & groups', 'Non-profits, Associations & Groups'), ('real estate', 'Real Estate'), ('retailers, resellers & sales', 'Retailers, Resellers & Sales'), ('web, tech & media', 'Web, Tech & Media'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
