# Generated by Django 3.1.7 on 2023-03-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0005_auto_20230329_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='address',
        ),
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
