# Generated by Django 3.2.18 on 2023-04-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0006_alter_companyprofile_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='smeApp.job'),
        ),
    ]
