# Generated by Django 3.2.18 on 2023-04-17 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0007_expense_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='date_joined',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='num_employees',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2-10', '2-10'), ('11-50', '11-50'), ('51-200', '51-199'), ('200+', '200+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
