# Generated by Django 3.2.18 on 2023-04-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0007_auto_20230331_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Repairs and Maintenance', 'Repairs and Maintenance'), ('Payroll', 'Payroll'), ('Meals and Entertainment', 'Meals and Entertainment'), ('Telephone', 'Telephone'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Advertising and Promotion', 'Advertising and Promotion'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sale', 'Sale'), ('Service', 'Service'), ('Product', 'Product'), ('Other', 'Other')], default='Sale', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unique_identifier',
        ),
    ]
