# Generated by Django 3.2.18 on 2023-04-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0008_auto_20230417_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='smeApp.job'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Late Payment', 'Late Payment'), ('Pending Payment', 'Pending Payment'), ('Overdue', 'Overdue'), ('Not Yet Invoiced', 'Not Yet Invoiced'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled'), ('Other', 'Other')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeApp.client'),
        ),
    ]
