# Generated by Django 3.2.18 on 2023-04-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0009_auto_20230417_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('receive_by_date', models.DateField(verbose_name='Receive By Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100, verbose_name='Order Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='smeApp.companyprofile', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(help_text='The date the sale was made.', verbose_name='Sale Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeApp.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='smeApp.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('address', models.CharField(blank=True, help_text='Street address, city, and zip code.', max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='smeApp.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Item ID')),
                ('name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('type', models.CharField(max_length=255, verbose_name='Item Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock_items/', verbose_name='Item Image')),
                ('barcode', models.CharField(blank=True, help_text='Optional barcode for the item.', max_length=255, null=True, verbose_name='Barcode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Selling Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity in Inventory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='smeApp.companyprofile', verbose_name='Company')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='smeApp.supplier', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The number of items sold in this transaction.', verbose_name='Quantity Sold')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeApp.expense')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='smeApp.sale')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeApp.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The number of items ordered.', verbose_name='Quantity Ordered')),
                ('unit_purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Purchase Cost')),
                ('total_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Purchase Price')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeApp.expense')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='smeApp.purchaseorder', verbose_name='Purchase Order')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeApp.stockitem', verbose_name='Stock Item')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeApp.supplier', verbose_name='Supplier'),
        ),
    ]
