# Generated by Django 3.2.18 on 2023-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0011_auto_20230419_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='business_type',
            field=models.CharField(choices=[('service', 'Service'), ('sales', 'Sales')], default='service', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='revenue_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='revenue_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('Other', 'Other')], default='Employee', max_length=10),
        ),
    ]
