# Generated by Django 3.2.18 on 2023-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0014_jobitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Late Payment', 'Late Payment'), ('Pending Payment', 'Pending Payment'), ('Overdue', 'Overdue'), ('Not Yet Invoiced', 'Not Yet Invoiced'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
