# Generated by Django 3.2.18 on 2023-05-12 02:07

from django.db import migrations

def update_existing_data(apps, schema_editor):
    CompanyProfile = apps.get_model('smeApp', 'CompanyProfile')
    for profile in CompanyProfile.objects.all():
        if profile.industry == 'art, photography & creative':
            profile.industry = 'art'
        elif profile.industry == 'construction & home improvement':
            profile.industry = 'construction'
        elif profile.industry == 'consulting & professional':
            profile.industry = 'consulting'
        elif profile.industry == 'financial services & insurance':
            profile.industry = 'financial'
        elif profile.industry == 'hair, spa & aesthetics':
            profile.industry = 'hair_spa'
        elif profile.industry == 'non-profits, associations & groups':
            profile.industry = 'non_profit'
        elif profile.industry == 'real estate':
            profile.industry = 'real_estate'
        elif profile.industry == 'retailers, resellers & sales':
            profile.industry = 'retail'
        elif profile.industry == 'web, tech & media':
            profile.industry = 'web_tech'
        elif profile.industry == 'other':
            profile.industry = 'other'

        if profile.num_employees == '1':
            profile.num_employees = '1'
        elif profile.num_employees == '2-10':
            profile.num_employees = '2_to_10'
        elif profile.num_employees == '11-50':
            profile.num_employees = '11_to_50'
        elif profile.num_employees == '51-199':
            profile.num_employees = '51_to_200'
        elif profile.num_employees == '200+':
            profile.num_employees = '200_plus'

        if profile.business_type == 'Service':
            profile.business_type = 'service'
        elif profile.business_type == 'Sales':
            profile.business_type = 'sales'

        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0016_auto_20230511_2147'),
    ]

    operations = [
    ]
