# Generated by Django 3.2.18 on 2023-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeApp', '0018_auto_20230511_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(choices=[('art', 'Art, Photography & Creative Services'), ('construction', 'Construction & Home Improvement'), ('consulting', 'Consulting & Professional Services'), ('financial', 'Financial Services & Insurance'), ('hair_spa', 'Hair, Spa & Aesthetics'), ('non_profit', 'Non-profits, Associations & Groups'), ('real_estate', 'Real Estate'), ('retail', 'Retailers, Resellers & Sales'), ('web_tech', 'Web, Tech & Media'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='num_employees',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2_to_10', '2-10'), ('11_to_50', '11-50'), ('51_to_200', '51-199'), ('200_plus', '200+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
