from django.urls import include, path
from . import views
from .views import(JobListView,
                    JobCreateView,
                    JobUpdateView,
                    JobDeleteView,
                    DashboardView,
                    JobDetailView,
                    IncomeUpdateView,
                    ExpenseUpdateView,
                    IncomeDeleteView,
                    ExpenseDeleteView,
                    TransactionsView,
                    ExpensesDataView,
                    ClientsListView,
                    ClientsList,
                    CompanyProfileCreateView,
                    ClientCreateView,
                    ClientUpdateView,
                    ClientDeleteView, AddJobNoteView, GetNoteView, UpdateNoteView, DeleteNoteView)

app_name = 'smeApp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('main-dashboard/', views.MainDashboardView.as_view(), name='main_dashboard'),
    path('jobs/json/', views.jobs_to_json, name='jobs_to_json'),
    path('create_company_profile/', CompanyProfileCreateView.as_view(), name='create_company_profile'),
    path('company_profile/', views.CompanyProfileDetailView.as_view(), name='company_profile_detail'),
    path('company_profile/edit/', views.CompanyProfileUpdateView.as_view(), name='company_profile_edit'),
    path('company_profile/delete/', views.CompanyProfileDeleteView.as_view(), name='company_profile_delete'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/edit/', views.UserProfileUpdateView.as_view(), name='edit_profile'),
    path('profile/edit-avatar/', views.EditAvatarView.as_view(), name='edit_avatar'),
    path('profile/delete/', views.UserProfileDeleteView.as_view(), name='delete_profile'),
    path('jobs/', JobListView.as_view(), name='job_list'),
    path('jobs/add/', JobCreateView.as_view(), name='job_add'),
    path('jobs/edit/<int:pk>/', JobUpdateView.as_view(), name='job_edit'),
    path('jobs/delete/<int:pk>/', JobDeleteView.as_view(), name='job_delete'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job_detail'),
    path('client/create/', views.client_create, name='client_create'),
    path('clients/create/', ClientCreateView.as_view(), name='clients_add'),
    path('client/<int:pk>/', views.ClientDetailView.as_view(), name='client-detail'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client-update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client-delete'),
    path('clients_list/', ClientsListView.as_view(), name='clients_list'),
    path('clients/', ClientsList.as_view(), name='client_list'),
    path('add_expense/', views.AddExpenseView.as_view(), name='add_expense'),
    path('add_expense/<data>/', views.AddExpenseView.as_view(), name='add_expense_prefilled'),
    path('expense-list/', views.ExpenseListView.as_view(), name='expense_list'),
    path('expense/<int:pk>/', views.ExpenseDetailView.as_view(), name='expense_detail'),
    path('add_income/', views.AddIncomeView.as_view(), name='add_income'),
    path('transactions/', views.TransactionsView.as_view(), name='transactions'),
    path('income/update/<int:pk>/', IncomeUpdateView.as_view(), name='income-update'),
    path('expense/update/<int:pk>/', ExpenseUpdateView.as_view(), name='expense-update'),
    path('income/delete/<int:pk>/', IncomeDeleteView.as_view(), name='income-delete'),
    path('expense/delete/<int:pk>/', ExpenseDeleteView.as_view(), name='expense-delete'),
    path('expenses_data/', ExpensesDataView.as_view(), name='expenses_data'),
    path('profit_loss_data/', views.ProfitLossDataView.as_view(), name='profit_loss_data'),
    path('invoices/', views.InvoiceListView.as_view(), name='invoices_list'),
    path('job/<int:job_id>/create_invoice/', views.CreateJobInvoiceView.as_view(), name='create_job_invoice'),
    path('invoice/<int:pk>/update/', views.UpdateInvoiceView.as_view(), name='update_invoice'),
    path('invoice/<int:pk>/delete/', views.DeleteInvoiceView.as_view(), name='delete_invoice'),
    path('create_invoice/', views.CreateInvoiceView.as_view(), name='create_invoice'),
    path('view_invoice/<int:invoice_id>/', views.ViewInvoiceView.as_view(), name='view_invoice'),
    path('preview_invoice/<int:invoice_id>/', views.PreviewInvoiceView.as_view(), name='preview_pdf'),
    path('job/<int:pk>/add_note/', views.AddJobNoteView.as_view(), name='add_job_note'),
    path('note/<int:pk>/', GetNoteView.as_view(), name='get_note'),
    path('note/<int:pk>/update/', UpdateNoteView.as_view(), name='update_note'),
    path('note/<int:pk>/delete/', DeleteNoteView.as_view(), name='delete_note'),
    path('upload_receipt/', views.UploadReceiptView.as_view(), name='upload_receipt'),
    path('api/expense/delete/', views.expense_delete, name='api_expense_delete'),

    path('suppliers/', views.SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/create/', views.SupplierCreateView.as_view(), name='supplier_create'),
    path('suppliers/update/<int:pk>/', views.SupplierUpdateView.as_view(), name='supplier_update'),
    path('suppliers/delete/<int:pk>/', views.SupplierDeleteView.as_view(), name='supplier_delete'),

    path('stock-items/', views.StockItemListView.as_view(), name='stock_item_list'),
    path('stock-items/create/', views.StockItemCreateView.as_view(), name='stock_item_create'),
    path('stock-items/update/<str:pk>/', views.StockItemUpdateView.as_view(), name='stock_item_update'),
    path('stock-items/delete/<str:pk>/', views.StockItemDeleteView.as_view(), name='stock_item_delete'),

    path('purchase-orders/', views.PurchaseOrderListView.as_view(), name='purchase_order_list'),
    path('purchase-orders/create/', views.PurchaseOrderCreateView.as_view(), name='purchase_order_create'),
    path('purchase-orders/update/<int:pk>/', views.PurchaseOrderUpdateView.as_view(), name='purchase_order_update'),
    path('purchase-orders/delete/<int:pk>/', views.PurchaseOrderDeleteView.as_view(), name='purchase_order_delete'),

    path('sales/', views.SaleListView.as_view(), name='sale_list'),
    path('sales/create/', views.SaleCreateView.as_view(), name='sale_create'),
    path('sales/update/<int:pk>/', views.SaleUpdateView.as_view(), name='sale_update'),
    path('sales/delete/<int:pk>/', views.SaleDeleteView.as_view(), name='sale_delete'),

    path('product-types/', views.ProductTypeListView.as_view(), name='product_type_list'),
    path('product-types/create/', views.ProductTypeCreateView.as_view(), name='product_type_create'),
    path('product-types/update/<int:pk>/', views.ProductTypeUpdateView.as_view(), name='product_type_update'),
    path('product-types/delete/<int:pk>/', views.ProductTypeDeleteView.as_view(), name='product_type_delete')

]
